name: "[PUSH] Sync (dev/uat)"
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [dev, uat]
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
          
      # Create pull request
      - name: Create pull request
        id: create-pr
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FROM_BRANCH: ${{ github.ref_name }}
          TO_BRANCH: ${{ matrix.branch }}
          PULL_REQUEST_TITLE: '[CI] Auto-merge from ${{ github.ref_name }} → ${{ matrix.branch }}'
          PULL_REQUEST_BODY: '[CI] Auto-merge from ${{ github.ref_name }} → ${{ matrix.branch }}'

      # Merge PR
      - name: Merge pull request
        if: steps.create-pr.outputs.PULL_REQUEST_NUMBER
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.DEPLOYMENT_PAT }}
          number: ${{ steps.create-pr.outputs.PULL_REQUEST_NUMBER }}
          method: merge
